name: Build and Release Mod

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name (e.g. v1.0.6)'
        required: true
        default: 'v1.0.6'

permissions:
  contents: write

env:
  RELEASE_VERSION: ${{ github.event.inputs.version || 'v1.0.6' }}

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild DllWrapper.sln /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false

    - name: Create ZIP Archive
      run: Compress-Archive -Path x64\Release\dxgi.dll, walkingman.ini -DestinationPath walkingman_${{ env.RELEASE_VERSION }}.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        name: ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
        files: walkingman_${{ env.RELEASE_VERSION }}.zip
