name: Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild DllWrapper.sln /p:Configuration=Release /p:Platform=x64 /p:PostBuildEventUseInBuild=false

    - name: Create ZIP Archive
      run: Compress-Archive -Path x64\Release\dxgi.dll, walkingman.ini -DestinationPath walkingman_${{ github.ref_name }}.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: walkingman_${{ github.ref_name }}.zip
